name: ruby
on: [push, pull_request]

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} (${{ matrix.gemfile }})
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        ruby: ["2.7", "3.0", "3.1"]

        gemfile:
          - "rails_6_1"
          - "rails_7_0"
          - "rails_head"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ matrix.ruby }}

      - name: Run tests
        run: bundle exec rake
